### ISSUE TITLE
Strategies to reduce overhead

### ISSUE THREAD

**Issue by jondot** [steelbrain/consistent-env#19]
Hi,

I'm using `zsh`, and much to my blame, I'm a polyglot programmer. This means I have rbenv, nvm, pyenv, and more tied to my `zshrc`, which makes a new shell startup very slow and painful.

The environment resolution in this module bubbles up to `linter` which then bubbles up to the respective linter I'm using (in this case `linter-rubocop`)

https://github.com/AtomLinter/linter-rubocop/issues/178

Other strategies that involves _not_ sourcing `zshrc` are quicker (namely, `zsh -c env`) but I'm sure there was a good reason why that wasn't used.

WDYT?

**Comment by steelbrain** [comment]
`zsh -c env` doesn't work with MacOSX as it doesn't provide the env vars correctly to all gui apps.

What you can do to speed up the process though is to check in your shell inclusion scripts **if stdout is a tty**.

As an example, you should not source `prezto` or `oh-my-zsh` if stdout is not tty, You can use [this](http://stackoverflow.com/a/911224/2652018) method to do so

Before (in profile scripts)
```
source ~/.zpreztoz/something
```
After
```
if [ -t 1 ]; then
  source ~/.zpreztoz/something
fi
```

Closing as this is not really a bug but feel free to continue discussing

**Comment by jondot** [comment]
Thanks, tty check sounds like a great idea!

**Comment by matrixik** [comment]
At last I found what was taking my system to almost halt with dozens of sourcing .zshrc processes. My `.zshrc` file is over 600 lines long and checking if stdout is a tty fix the problem.

**Comment by matrixik** [comment]
@steelbrain maybe you could detect operating system of user and on Linux use `zsh -c env` to avoid problems for other *heavy* users.

**Comment by Arcanemagus** [comment]
@matrixik If you were hitting this then there was a problem with your init script that was making it run interactive only code in non-interactive shells. The fact that this package is what exposed that is just a side note, the problem was in your configuration.

**Comment by matrixik** [comment]
Oh, OK, one big `if` fixed it. Thank you.
